import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  final Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  final Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [newTheme].
  void changeTheme(String newTheme) {
    _appTheme = newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: colorScheme.onError,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.blueA700,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(30.h),
          ),
          shadowColor: colorScheme.primary,
          elevation: 2,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.blueGray200.withOpacity(0.2),
            width: 2.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(30.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: WidgetStateColor.resolveWith((states) {
          if (states.contains(WidgetState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: const BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 2,
        space: 2,
        color: appTheme.blueA700,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.gray700,
          fontSize: 16.fSize,
          fontFamily: 'Montserrat',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.gray800,
          fontSize: 14.fSize,
          fontFamily: 'Mulish',
          fontWeight: FontWeight.w400,
        ),
        headlineLarge: TextStyle(
          color: appTheme.indigo700,
          fontSize: 30.fSize,
          fontFamily: 'Aubrey',
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.onErrorContainer.withOpacity(1),
          fontSize: 24.fSize,
          fontFamily: 'Jost',
          fontWeight: FontWeight.w600,
        ),
        labelLarge: TextStyle(
          color: appTheme.gray700,
          fontSize: 13.fSize,
          fontFamily: 'Mulish',
          fontWeight: FontWeight.w800,
        ),
        labelMedium: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 11.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
        ),
        labelSmall: TextStyle(
          color: appTheme.blueGray90001,
          fontSize: 9.fSize,
          fontFamily: 'Mulish',
          fontWeight: FontWeight.w800,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onErrorContainer.withOpacity(1),
          fontSize: 21.fSize,
          fontFamily: 'Jost',
          fontWeight: FontWeight.w600,
        ),
        titleMedium: TextStyle(
          color: appTheme.gray800,
          fontSize: 18.fSize,
          fontFamily: 'Mulish',
          fontWeight: FontWeight.w800,
        ),
        titleSmall: TextStyle(
          color: appTheme.gray700,
          fontSize: 14.fSize,
          fontFamily: 'Mulish',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static const primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF0961F5),
    primaryContainer: Color(0XFF1C1C1B),
    secondaryContainer: Color(0XFF545454),

    // Error colors
    errorContainer: Color(0XFFFCC202),
    onError: Color(0XFFFFFFFF),
    onErrorContainer: Color(0XCC202244),

    // On colors(text colors)
    onPrimary: Color(0XFF1F0E31),
    onPrimaryContainer: Color(0XFF1DA1F2),
    onSecondaryContainer: Color(0XFF0E0E0E),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amberA400 => const Color(0XFFFFC200);
  Color get amberA200 => const Color(0XFFFAC840);
  Color get amberA20001 => const Color(0XFFFCCB40);

  // Black
  Color get black900 => const Color(0XFF000000);

  // Blue
  Color get blue50 => const Color(0XFFE8F1FF);
  Color get blue600 => const Color(0XFF1B97DF);
  Color get blueA400 => const Color(0XFF1A6EFB);
  Color get blueA40001 => const Color(0XFF1A6EFC);
  Color get blueA700 => const Color(0XFF0961F5);

  // BlueGray
  Color get blueGray100 => const Color(0XFFD7D7D7);
  Color get blueGray200 => const Color(0XFFB4BDC4);
  Color get blueGray900 => const Color(0XFF333333);
  Color get blueGray90001 => const Color(0XFF202244);

  // Gray
  Color get gray100 => const Color(0XFFF3F3F3);
  Color get gray50 => const Color(0XFFF4F8FE);
  Color get gray700 => const Color(0XFF545454);
  Color get gray800 => const Color(0XFF505050);

  Color get gray200 => const Color(0XFFEAEAEA);

  Color get gray500 => const Color(0XFFA0A4AB);
  Color get gray5001 => const Color(0XFFF4F8FE);
  Color get gray5002 => const Color(0XFFF5F9FF);

  Color get gray80001 => const Color(0XFF472D2D);
  Color get gray900 => const Color(0XFF1C1C1B);

  // Indigo
  Color get indigo700 => const Color(0XFF332DA1);
  Color get indigo500 => const Color(0XFF3046CC);
  Color get indigo50001 => const Color(0XFF4267B2);
  // Orange
  Color get orange100 => const Color(0XFFF8DCA3);
  Color get orangeA700 => const Color(0XFFFF6B00);
  Color get orangeA200 => const Color(0XFFEBB039);
  // Red
  Color get red500 => const Color(0XFFF04336);
  Color get redA400 => const Color(0XFFFF001E);
  Color get red600 => const Color(0XFFDB4A39);
  // Teal
  Color get teal50 => const Color(0XFFD5E1F5);
  Color get teal700 => const Color(0XFF167F71);
  Color get teal600 => const Color(0XFF128C7E);
  // White
  Color get whiteA700 => const Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
